/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Animateria (https://sketchfab.com/Animateria)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/artist-workroom-e0c52b6adf1245f2b36f5f49cddb56b9
title: Artist workroom
*/

import { useGLTF } from '@react-three/drei';
import Room from './artist_workroom-old1.glb';

export function Model(props) {
  const { nodes, materials } = useGLTF(Room)
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.01}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Against_door_Against_door_0.geometry}
              material={materials.Against_door}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Against_door_Glass_Against_door_Glass_0.geometry}
              material={materials.Against_door_Glass}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Brick_Wall_Brick_wall_0.geometry}
              material={materials.Brick_wall}
            />
          </group>
          <group
            position={[130, 86.37, -40]}
            rotation={[3.03, 0.69, 1.64]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Brush_0_Brush_0_0.geometry}
              material={materials.Brush_0}
            />
          </group>
          <group
            position={[129.13, 81, -20.81]}
            rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Brush_Box_Brush_Box_0.geometry}
              material={materials.Brush_Box}
            />
          </group>
          <group
            position={[160.61, 81.05, -49.16]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Brushs_pot_Brushs_pot_0.geometry}
              material={materials.Brushs_pot}
            />
          </group>
          <group
            position={[123.47, 81, -79.33]}
            rotation={[-Math.PI / 2, 0, -2.44]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.C_Box_C_Box_0.geometry}
              material={materials.C_Box}
            />
          </group>
          <group
            position={[-51.28, 165.67, -46.94]}
            rotation={[-1.66, -0.25, -0.35]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Canvas_White_Canvas_White_0.geometry}
              material={materials.Canvas_White}
            />
          </group>
          <group
            position={[10, 0, -40.55]}
            rotation={[-Math.PI / 2, 0, 0.09]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Circular_Carpet_Circular_Carpet_0.geometry}
              material={materials.Circular_Carpet}
            />
          </group>
          <group
            position={[147.65, 81.14, -107.54]}
            rotation={[-Math.PI / 2, 0, Math.PI]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Coffee_Coffee_0.geometry}
              material={materials.Coffee}
            />
          </group>
          <group
            position={[61.02, 16.4, 139.99]}
            rotation={[-Math.PI / 2, 0, 1.75]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Fitment_Fitment_0.geometry}
              material={materials.Fitment}
            />
          </group>
          <group
            position={[-150.48, 283.05, -96.11]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 6]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Flowerpots_shelfs_Flowerpots_shelfs_0.geometry}
              material={materials.Flowerpots_shelfs}
            />
          </group>
          <group
            position={[-137.1, 280.07, -133.31]}
            rotation={[-Math.PI / 2, 0, 0.57]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Flowers_Flowers_0.geometry}
              material={materials.Flowers}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Green_Wall_Green_Wall_0.geometry}
              material={materials.Green_Wall}
            />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Hardwood_floor_Hardwood_floor_0.geometry}
              material={materials.Hardwood_floor}
            />
          </group>
          <group
            position={[10.62, 364.25, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Lamps_Lamps_Light_0.geometry}
              material={materials.Lamps_Light}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Lamps_Lamps_Base_0.geometry}
              material={materials.Lamps_Base}
            />
          </group>
          <group position={[-23.27, 316.17, -351.28]} scale={100}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group
            position={[44.28, 25, 130.2]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Paint_Pot_Paint_Pot_0.geometry}
              material={materials.material_0}
            />
          </group>
          <group
            position={[-72.96, 19, -29.5]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Paint_Pot_Group_Paint_Pot_Group_0.geometry}
              material={materials.Paint_Pot_Group}
            />
          </group>
          <group
            position={[-158, 223.05, -101.31]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Paint_Pot_Group_2_Paint_Pot_Group_2_0.geometry}
              material={materials.Paint_Pot_Group_2}
            />
          </group>
          <group
            position={[-161.29, 177.4, 71.16]}
            rotation={[-Math.PI / 2, -0.09, 0]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Painting_1_Painting_1_0.geometry}
              material={materials.Painting_1}
              position={[-0.09, 0, 0.01]}
              rotation={[0, 0.09, 0]}
            />
          </group>
          <group
            position={[158.06, 262.66, -182.36]}
            rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Painting_2_Painting_2_0.geometry}
              material={materials.Painting_2}
            />
          </group>
          <group
            position={[-119.34, 38.03, -252.79]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Palm_Palm_0.geometry}
              material={materials.Palm}
            />
          </group>
          <group
            position={[-120, 17.35, -253.31]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Palm_flowerpot_Palm_flowerpot_0.geometry}
              material={materials.Palm_flowerpot}
            />
          </group>
          <group
            position={[138.97, 81.53, -63.59]}
            rotation={[-Math.PI / 2, 0, 0.17]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Rag_Rag_0.geometry}
              material={materials.material}
            />
          </group>
          <group position={[10.29, 326.15, -5.1]} scale={100}>
            <group rotation={[Math.PI / 2, 0, 0]} />
          </group>
          <group
            position={[47.92, 17.14, -130]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Seat_wood_Seat_wood_0.geometry}
              material={materials.Seat_wood}
            />
          </group>
          <group
            position={[-161.53, 235.15, -103.52]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Shelfs_Shelfs_0.geometry}
              material={materials.Shelfs}
            />
          </group>
          <group
            position={[147.44, 16.4, -60]}
            rotation={[-Math.PI / 2, 0, 0.09]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Table_Table_0.geometry}
              material={materials.Table}
            />
          </group>
          <group
            position={[0, 0, -253.5]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Terrace_floor_Terrace_floor_0.geometry}
              material={materials.Terrace_floor}
            />
          </group>
          <group
            position={[-81.21, 14.79, -56.94]}
            rotation={[-Math.PI / 2, 0, 1.23]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Trestle_Trestle_0.geometry}
              material={materials.Trestle}
            />
          </group>
          <group
            position={[0, 5.24, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Woods_Top_Down_Woods_Top_Down_0.geometry}
              material={materials.Woods_Top_Down}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload(Room)
